name: Cypress Tests

on:
  pull_request:
    branches: [main]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cypress install
        uses: cypress-io/github-action@v6
        with:
          runTests: false
          build: npm run build

      - name: Save node_modules and build folder
        uses: actions/upload-artifact@v4
        with:
          name: build-and-deps
          if-no-files-found: error
          include-hidden-files: true
          path: |
            node_modules
            .next

  cypress-run:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:22.12.0
      options: --user 1001
    needs: install

    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4]

    steps:
      - uses: actions/checkout@v4

      - name: Download node_modules and build folder
        uses: actions/download-artifact@v4
        with:
          name: build-and-deps

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          record: true
          parallel: true
          group: "UI-Chrome"
          start: npm start
          wait-on: "http://localhost:3000"
          browser: chrome
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_INFO_MESSAGE: ${{ github.event.pull_request.title }}
          COMMIT_INFO_SHA: ${{ github.event.pull_request.head.sha }}
