name: Cypress Tests

on:
  pull_request:
    branches: [main]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cypress install
        uses: cypress-io/github-action@v6
        with:
          runTests: false
          build: npm run build

      - name: Save node_modules and build folder
        uses: actions/upload-artifact@v4
        with:
          name: build-and-deps
          if-no-files-found: error
          include-hidden-files: true
          path: .next

  generate-specs:
    runs-on: ubuntu-latest
    outputs:
      specs: ${{ steps.set-specs.outputs.specs }}
    steps:
      - uses: actions/checkout@v4
      - id: set-specs
        run: |
          SPECS=$(find cypress/e2e -name "*.cy.ts" -printf '"%p",')
          SPECS="[${SPECS%,}]"
          echo "specs=$SPECS" >> $GITHUB_OUTPUT

  cypress-run:
    runs-on: ubuntu-latest
    needs:
      - install
      - generate-specs
    container:
      image: cypress/browsers:22.12.0
      options: --user 1001

    strategy:
      fail-fast: false
      matrix:
        spec: ${{ fromJson(needs.generate-specs.outputs.specs) }}

    steps:
      - uses: actions/checkout@v4

      - name: Download node_modules and build folder
        uses: actions/download-artifact@v4
        with:
          name: build-and-deps

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
          wait-on: "http://localhost:3000"
          browser: chrome
          spec: ${{ matrix.spec }}

      - name: Save screenshots (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Save videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
