name: Cypress Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cypress install
        uses: cypress-io/github-action@v6
        with:
          runTests: false
          build: npm run build

      - name: Save node_modules and build folder
        uses: actions/upload-artifact@v4
        with:
          name: build-and-deps
          if-no-files-found: error
          include-hidden-files: true
          path: |
            node_modules
            .next

  cypress-run:
    runs-on: ubuntu-latest
    needs: install

    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4]

    steps:
      - uses: actions/checkout@v4

      - name: Download node_modules and build folder
        uses: actions/download-artifact@v4
        with:
          name: build-and-deps

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          browser: chrome
