name: Build and Test code on pull request

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

    strategy:
      matrix:
        node-version: ["18.x", "20.x", "22.x"]

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
            .next/cache
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-

      - name: ⎔ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: 📦 Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: 🛠 Run build
        run: npm run build --if-present

      - name: 🧪 Run tests with coverage
        run: npm test -- --coverage --test-concurrency=4

      - name: 📤 Upload coverage report to Codecov
        uses: codecov/codecov-action@v5
        with:
          slug: who0803/practice-ci-cd
          fail_ci_if_error: true
